import InfoboxUrl from "../../assets/images/info_box_image.svg";

const dummyGenerationData = {
  staff: [
    {
      sectionTitle: "대표",
      members: [
        {
          id: 1,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "부대표",
      members: [
        {
          id: 2,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "PO",
      members: [
        {
          id: 3,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 4,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 5,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 6,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "FRONTEND",
      members: [
        {
          id: 7,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 8,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 9,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "BACKEND",
      members: [
        {
          id: 10,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 11,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 12,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
  ],

  babyLion: [
    {
      sectionTitle: "PO",
      members: [
        {
          id: 13,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 14,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 15,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 16,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 17,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 18,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 19,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "FRONTEND",
      members: [
        {
          id: 20,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 21,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 22,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 23,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 24,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 25,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 26,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 27,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 28,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 29,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 30,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 31,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
    {
      sectionTitle: "BACKEND",
      members: [
        {
          id: 32,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 33,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 34,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 35,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 36,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 37,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 38,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 39,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 40,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 41,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 42,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
        {
          id: 43,
          name: "홍길동",
          department: "디자인학부",
          studentId: "00학번",
          image: InfoboxUrl,
        },
      ],
    },
  ],
};

export const membersData = {
  14: {
    staff: [
      {
        sectionTitle: "대표",
        members: [
          {
            id: "staff-leader-1",
            name: "윤희준",
            department: "소프트웨어학과",
            studentId: "20학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "부대표",
        members: [
          {
            id: "staff-vice-leader-1",
            name: "임다현",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "PO",
        members: [
          {
            id: "staff-po-1",
            name: "정영진",
            department: "디자인학부 비주얼디자인전공",
            studentId: "20학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-po-2",
            name: "최운조",
            department: "비주얼디자인전공",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-po-3",
            name: "임다현",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-po-4",
            name: "김정현",
            department: "아트앤테크놀로지학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "FRONTEND",
        members: [
          {
            id: "staff-frontend-1",
            name: "심서현",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-frontend-2",
            name: "정목진",
            department: "소프트웨어학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-frontend-3",
            name: "김현수",
            department: "소프트웨어학과",
            studentId: "25학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "BACKEND",
        members: [
          {
            id: "staff-backend-1",
            name: "금시언",
            department: "소프트웨어학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-backend-2",
            name: "신채린",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "staff-backend-3",
            name: "김나경",
            department: "소프트웨어학과 공공인재학부",
            studentId: "22학번",
            image: InfoboxUrl,
          },
        ],
      },
    ],

    babyLion: [
      {
        sectionTitle: "PO",
        members: [
          {
            id: "baby-po-1",
            name: "조재호",
            department: "소프트웨어학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-2",
            name: "한슬기",
            department: "미래융합학부 IT계열",
            studentId: "25학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-3",
            name: "박세은",
            department: "미래융합학부 IT계열",
            studentId: "25학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-4",
            name: "구나영",
            department: "비주얼디자인학과",
            studentId: "24학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-5",
            name: "엄다영",
            department: "아트앤테크놀로지",
            studentId: "26학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-6",
            name: "조민서",
            department: "미래융합학부2",
            studentId: "26학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-7",
            name: "강서연",
            department: "시각정보디자인전공",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-po-8",
            name: "이정민",
            department: "비주얼디자인학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "FRONTEND",
        members: [
          {
            id: "baby-frontend-1",
            name: "최서연",
            department: "소프트웨어학과",
            studentId: "24학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-2",
            name: "백윤관",
            department: "소프트웨어학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-3",
            name: "김서현",
            department: "소프트웨어학과",
            studentId: "24학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-4",
            name: "김민솔",
            department: "소프트웨어학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-5",
            name: "김우현",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-6",
            name: "홍윤지",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-7",
            name: "한주은",
            department: "아동학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-8",
            name: "김승민",
            department: "소프트웨어학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-9",
            name: "양우석",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-10",
            name: "정시훈",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-11",
            name: "장서후",
            department: "소프트웨어학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-12",
            name: "양희창",
            department: "소프트웨어학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-13",
            name: "장경무",
            department: "전자컴퓨터공학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-frontend-14",
            name: "김윤정",
            department: "파이낸스앤테크학과",
            studentId: "25학번",
            image: InfoboxUrl,
          },
        ],
      },
      {
        sectionTitle: "BACKEND",
        members: [
          {
            id: "baby-backend-1",
            name: "이주희",
            department: "전자컴퓨터공학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-2",
            name: "최아원",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-3",
            name: "조민호",
            department: "소프트웨어학과",
            studentId: "24학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-4",
            name: "오지우",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-5",
            name: "남궁강",
            department: "컴퓨터공학과",
            studentId: "20학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-6",
            name: "이정능",
            department: "컴퓨터공학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-7",
            name: "최예윤",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-8",
            name: "이충환",
            department: "컴퓨터공학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-9",
            name: "김민호",
            department: "컴퓨터공학과",
            studentId: "22학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-10",
            name: "나형준",
            department: "소프트웨어학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-11",
            name: "김정모",
            department: "소프트웨어학과",
            studentId: "21학번",
            image: InfoboxUrl,
          },
          {
            id: "baby-backend-12",
            name: "김태현",
            department: "소프트웨어학과",
            studentId: "23학번",
            image: InfoboxUrl,
          },
        ],
      },
    ],
  },
  13: dummyGenerationData,
  12: dummyGenerationData,
  11: dummyGenerationData,
};
